// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvXzT5sQ1JPAiFNGrzofEzsLVxF7nBpw',
    appId: '1:427052467685:web:4b63b5640526fb12aadb0c',
    messagingSenderId: '427052467685',
    projectId: 'vision-b2bb0',
    authDomain: 'vision-b2bb0.firebaseapp.com',
    storageBucket: 'vision-b2bb0.appspot.com',
    measurementId: 'G-SP3B812GYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzfMfe3IRaZzEKZZZdnFHsejivUDa5Io',
    appId: '1:427052467685:android:f2e55074d65a6c05aadb0c',
    messagingSenderId: '427052467685',
    projectId: 'vision-b2bb0',
    storageBucket: 'vision-b2bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4jr8D3ungc-mAZUF3dUit4P9CkV1XJrY',
    appId: '1:427052467685:ios:dedc1a4829aad15faadb0c',
    messagingSenderId: '427052467685',
    projectId: 'vision-b2bb0',
    storageBucket: 'vision-b2bb0.appspot.com',
    iosClientId: '427052467685-8ljvcuuv9atdq3oa28pgac9lhd5li93b.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4jr8D3ungc-mAZUF3dUit4P9CkV1XJrY',
    appId: '1:427052467685:ios:dedc1a4829aad15faadb0c',
    messagingSenderId: '427052467685',
    projectId: 'vision-b2bb0',
    storageBucket: 'vision-b2bb0.appspot.com',
    iosClientId: '427052467685-8ljvcuuv9atdq3oa28pgac9lhd5li93b.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendApp',
  );
}
